########################################
## Custom models
########################################

Model\Token:
  itemOperations: []
  collectionOperations:
    post_auth_token_exchange:
      method: 'POST'
      path: '/token/exchange'
      route_name: 'post_auth_token_exchange'
      swagger_context:
        consumes:
        - 'application/x-www-form-urlencoded'
        produces:
        - 'application/json'
        tags:
        - Auth
        parameters:
        - name: token
          in: formData
          type: string
          required: true
          description: 'Brand admin token'
        - name: username
          in: formData
          type: string
          required: true
          description: 'Target client admin user name'

Model\WebTheme:
  itemOperations:
    get:
      method: 'GET'
      path: '/my/web_theme'
      route_name: 'get_my_web_theme'
      swagger_context:
        tags:
          - My
        parameters: []
  collectionOperations: {}

Model\UserStatus:
  attributes:
    access_control: '"ROLE_COMPANY_USER" in roles'
  itemOperations:
    get:
      method: 'GET'
      path: '/my/status'
      route_name: 'get_my_status'
      swagger_context:
        tags:
          - My
        parameters: []
  collectionOperations: {}

Model\CallStats:
  attributes:
    access_control: '"ROLE_COMPANY_USER" in roles'
  itemOperations:
    get:
      method: 'GET'
      path: '/my/call_stats'
      route_name: 'get_my_call_stats'
      swagger_context:
        tags:
          - My
        parameters: []
  collectionOperations: {}
